#!/usr/bin/env sh

set -x

# ====
# initialization
# ====
# Loading Scripting Additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

source ~/.config/yabai/scripts/initialization.sh

# ====
# Signals
# ====
# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/initialization.sh"

# ===== Rules   ==========

otherApp='^(IINA|Finder|Calendar|System Preferences|Mail|WeChat|QQ|Alfred Preferences|Todoist|Input Source Pro|Spotify|Activity Monitor|App Store|AppCleaner|Bitwarden|Bob|Calculator|Contexts|Dictionary|DingTalk|EuDic|Hammerspoon|Hidden Bar|mpv|Notes|OmniDiskSweeper|QuickTime Player|Reminders|Software Update|Stickies|The Unarchiver|Videos|Vimac|GeekTool)$'
yabai -m rule --add app="${otherApp}" manage=off

yabai -m rule --add label="About This Mac" app="^System Information$" manage=off
yabai -m rule --add label="External Alacritty" app="^alacritty$" title="^DapExternal$" manage=off
yabai -m rule --add label="DataGrip Welcome" app="^DataGrip IDEA$" title="^Welcome" manage=off
yabai -m rule --add label="DataGrip Keyboard Shortcut" app="^DataGrip IDEA$" title="^Keyboard Shortcut$" manage=off
yabai -m rule --add label="DataGrip Preferences" app="^DataGrip IDEA$" title="^Preferences" manage=off
yabai -m rule --add label="Intellij Add to" app="^IntelliJ IDEA$" title="^Add File to" manage=off
yabai -m rule --add label="Intellij Copy" app="^IntelliJ IDEA$" title="^Copy" manage=off
yabai -m rule --add label="Intellij Commit" app="^IntelliJ IDEA$" title="^Push Commits to" manage=off
yabai -m rule --add label="Intellij Project" app="^IntelliJ IDEA$" title="^Project" manage=off
yabai -m rule --add label="Intellij Rollback" app="^IntelliJ IDEA$" title="^Rollback" manage=off
yabai -m rule --add label="Intellij Update Project" app="^IntelliJ IDEA$" title="^Update Project$" manage=off
yabai -m rule --add label="Intellij Welcome" app="^IntelliJ IDEA$" title="^Welcome" manage=off
yabai -m rule --add label="Intellij Keyboard Shortcut" app="^IntelliJ IDEA$" title="^Keyboard Shortcut$" manage=off
yabai -m rule --add label="Intellij Preferences" app="^IntelliJ IDEA$" title="^Preferences" manage=off
yabai -m rule --add label="Karabiner" app="^Karabiner" manage=off
yabai -m rule --add label="Little Snitch" app="^Little Snitch" manage=off
yabai -m rule --add label="Surge" app="^Surge" manage=off

# ===== Tiling settings ==========
yabai -m config layout                       bsp

yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_topmost               off
yabai -m config window_shadow                float

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.95
yabai -m config normal_window_opacity        0.9

yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_animation_duration    0.0

yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config window_border_radius         8
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0x00ffffff

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config external_bar                 all:20:0
