#!/usr/bin/env sh

# ===== Loading Scripting Additions ==========
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling settings ==========
yabai -m config layout                       bsp

yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   1

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_topmost               off
yabai -m config window_shadow                float

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.9
yabai -m config normal_window_opacity        0.85

yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_animation_duration    0.0

yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config window_border_radius         2
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# ===== Rules   ==========
yabai -m rule --add label="About This Mac" app="^System Information$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Alfred" app="^Alfred" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="AppCleaner" app="^AppCleaner$" manage=off
yabai -m rule --add label="Bitwarden" app="^Bitwarden$" manage=off
yabai -m rule --add label="Bob" app="^Bob$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off
yabai -m rule --add label="Contexts" app="^Contexts$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="DingTalk" app="^DingTalk$" manage=off
yabai -m rule --add label="EuDic" app="^EuDic$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
yabai -m rule --add label="Hidden Bar" app="^Hidden Bar$" manage=off
yabai -m rule --add label="IINA" app="^IINA$" manage=off
yabai -m rule --add label="Intellij Welcome" app="^IntelliJ IDEA$" title="^Welcome" manage=off
yabai -m rule --add label="Intellij Keyboard Shortcut" app="^IntelliJ IDEA$" title="^Keyboard Shortcut$" manage=off
yabai -m rule --add label="Intellij Preferences" app="^IntelliJ IDEA$" title="^Preferences" manage=off
yabai -m rule --add label="Karabiner" app="^Karabiner" manage=off
yabai -m rule --add label="Little Snitch" app="^Little Snitch$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Notes" app="^Notes$" manage=off
yabai -m rule --add label="OmniDiskSweeper" app="^OmniDiskSweeper$" manage=off
yabai -m rule --add label="QQ" app="^QQ$" manage=off
yabai -m rule --add label="QuickTime Player" app="^QuickTime Player$" manage=off
yabai -m rule --add label="Software Update" app="^Software Update$" manage=off
yabai -m rule --add label="Stickies" app="^Stickies$" manage=off
yabai -m rule --add label="Surge" app="^Surge$" manage=off
yabai -m rule --add label="Surge Dashboard" app="^Surge Dashboard$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Videos" app="^Videos$" manage=off
yabai -m rule --add label="Vimac" app="^Vimac$" manage=off
yabai -m rule --add label="WeChat" app="^WeChat$" manage=off

