#!/usr/bin/env sh

# set -x

# sudo yabai --load-sa

# ===== Configs  =========

yabai -m config external_bar                 all:0:0

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_shadow                off

yabai -m config window_opacity               off

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# ===== Rules   ==========

yabai -m rule --add label="DingTalkSubWindow" app="DingTalk" title=".*" manage=off
yabai -m rule --add label="DingTalk" app="DingTalk" title="DingTalk" manage=on

yabai -m rule --add label="SystemInformation" app="System Information" manage=off
yabai -m rule --add label="SystemPreferences" app="System Preferences" manage=off
yabai -m rule --add label="SystemSettings" app="System Settings" manage=off
yabai -m rule --add label="SoftwareUpdate" app="Software Update" manage=off

# yabai -m rule --add label="IntellijDialog2" app="^IntelliJ IDEA$" title!=".*\[.*\].*" manage=off
yabai -m rule --add label="IntellijDialog1" app="^IntelliJ IDEA$" title="^[A-Z].*" manage=off
yabai -m rule --add label="IntellijMain" app="^IntelliJ IDEA$" title="^\w.* \[.*\] - .*" manage=on
yabai -m rule --add label="IntellijWelcome" app="^IntelliJ IDEA$" title="^Welcome.*" manage=on

yabai -m rule --add label="Karabiner" app="^Karabiner" manage=off
yabai -m rule --add label="Surge" app="^Surge" manage=off

yabai -m rule --add label="Alfred" app="Alfred Preferences" title="Alfred Preferences" manage=off

otherApp='^(IINA|Finder|Calendar|Mail|AppCleaner|Bitwarden|Calculator|Contexts|Dictionary|Hammerspoon|Hidden Bar|mpv|Notes|QuickTime Player|Reminders|Stickies|The Unarchiver|Videos|Vimac)$'
yabai -m rule --add app="${otherApp}" manage=off

# ===== Signals ==========
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/scripts/initialization"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/scripts/initialization"

yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_created action="sketchybar -m --trigger windows_on_spaces &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces &> /dev/null"

yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

source "$HOME/.config/yabai/scripts/initialization"

